sources:
  - name: webcam
    file_path: ./source/impl/webcam.py
    class_name: Webcam 
    parameters:
      device: "/dev/video0"
      width: 640
      height: 640 

operations:
  - name: Mitwelten Pipeline (Hailo)
    class_name: Mitwelten
    file_path: ./operation/impl/mitwelten_hailo.py
    parameters:
      flower_params:
        confidence_threshold: 0.5
        model_path: ./resources/ml_models/yolov8n_flower_ep50_v1.hef
        label_path: ./resources/labels/flower.txt
      pollinator_params:
        confidence_threshold: 0.5
        model_path: ./resources/ml_models/yolov8n_pollinator_ep50_v1.hef
        label_path: ./resources/labels/pollinator.txt
        batch_size: 4

sinks:
  - name: console
    class_name: Console
    file_path: ./sink/impl/console.py
