sources:
  - name: webcam
    file_path: ./source/impl/webcam.py
    class_name: Webcam 
    parameters:
      device: "/dev/video0"
      width: 640
      height: 640 
pipes:
  - name: Mitwelten Pipeline (ONNX)
    class_name: Mitwelten
    file_path: ./pipe/impl/mitwelten_onnx.py
    parameters:
      flower_params:
        confidence_threshold: 0.6
        model_path: ./resources/ml_models/flower_n.onnx 
        label_path: ./resources/labels/flower.txt
      pollinator_params:
        confidence_threshold: 0.6
        model_path: ./resources/ml_models/pollinator_simplified.onnx
        label_path: ./resources/labels/pollinator.txt
sinks:
  - name: console
    class_name: Console
    file_path: ./sink/impl/console.py

