sources:
  - name: aicamera 
    file_path: ./source/impl/aiCamera.py
    class_name: AiCamera
    parameters:
      width: 640
      height: 640 

pipes:
  - name: Mitwelten Pipeline (Hailo)
    class_name: Mitwelten
    file_path: ./pipe/impl/mitwelten_hailo.py
    parameters:
      flower_params:
        file_path: ./source/impl/aiCamera.py
        class_name: AiCamera
      pollinator_params:
        confidence_threshold: 0.5
        model_path: ./resources/ml_models/yolov8n_pollinator_ep50_v1.hef
        label_path: ./resources/labels/pollinator.txt
        batch_size: 4

sinks:
  - name: console
    class_name: Console
    file_path: ./sink/impl/console.py

