sources:
  # - name: aicamera 
  #   file_path: ./source/impl/aiCamera.py
  #   class_name: AiCamera
  #   parameters:
  #     width: 640
  #     height: 640 
  - name: default
    file_path: ./source/impl/opencv.py
    class_name: OpenCVCamera
    parameters:
      device: "/dev/video0"
      width: 640
      height: 640 
  - name: pi
    class_name: PiCamera
    file_path: ./source/impl/pi.py
    parameters:
      width: 640
      height: 640
  - name: static_image
    class_name: StaticFrameGenerator
    file_path: ./source/impl/static.py
steps:
  - name: dummy - draw center rectangle
    class_name: Dummy
    file_path: ./ml/impl/dummy.py
    input_id: raw_image
    output_id: rectangle
    task: detection 
  - name: hailo
    class_name: HailoObjectDetection
    file_path: ./ml/impl/hailoObjectDetection.py
    input_id: raw_image
    output_id: hailo_output
    task: detection 
    parameters:
      confidence: 0.5
      #  - name: detect coco objects
      #    class_name: UlObjectDetection
      #    file_path: ./ml/impl/ulObjectDetection.py
      #    input_id: raw_image
      #    output_id: car_results
      #    task: detection 
      #    parameters:
      #      confidence_threshold: 0.5
      #      nms_threshold: 0.3
      #  - name: ai camera
      #    class_name: AiCamera
      #    file_path: ./source/impl/aiCamera.py
      #    input_id: raw_image
      #    output_id: ai_camera_results
      #    task: detection 
      #    parameters:
      #      confidence_threshold: 0.5
      #      nms_threshold: 0.3
  # - name: detect person objects
  #   class_name: PersonObjectDetection
  #   file_path: ./ml/impl/personObjectDetection.py
  #   task: detection 
  #   input_id: image
  #   output_id: car_detections
  #   parameters:
  #     confidence_threshold: 0.8
  #     nms_threshold: 0.4
  # - name: detect person objects
  #   class_name: PersonObjectDetection
  #   file_path: ./ml/impl/personObjectDetection.py
  #   input_id: car_detections
  #   task: detection 
  #   output_id: person_detections
  #   parameters:
  #     confidence_threshold: 0.8
  #     nms_threshold: 0.4
  # - name: detect person keypoints
  #   class_name: PersonKeypoints
  #   file_path: ./ml/impl/personKeypoints.py
  #   input_id: person_detections
  #   output_id: person_keypoints
  #   task: pose 
  #   parameters:
  #     confidence_threshold: 0.8
sinks:
  - name: console
    class_name: Console
    file_path: ./sink/impl/console.py
  - name: webserver
    class_name: WebServer
    file_path: ./api/server.py
    parameters:
      host: 0.0.0.0
      port: 8000
